### ISSUE TITLE
building problem

### ISSUE THREAD

**Issue by json1c** [crpmax/mc-bots#26]
```gradle build --info
Initialized native services in: /root/.gradle/native
The client will now receive all logging from the daemon (pid: 586242). The daemon log file: /root/.gradle/daemon/6.4.1/daemon-586242.out.log
Starting 5th build in daemon [uptime: 5 mins 15.803 secs, performance: 97%, non-heap usage: 24% of 268,4 MB]
Using 3 worker leases.
Starting Build
Settings evaluated using settings file '/root/mc-bots/settings.gradle'.
Projects loaded. Root project using build file '/root/mc-bots/build.gradle'.
Included projects: [root project 'mc-bots']

> Configure project :
Evaluating root project 'mc-bots' using build file '/root/mc-bots/build.gradle'.
All projects evaluated.
Selected primary task 'build' from project :
Tasks to be executed: [task ':compileJava', task ':processResources', task ':classes', task ':jar', task ':assemble', task ':compileTestJava', task ':processTestResources', task ':testClasses', task ':test', task ':check', task ':build']
Tasks that were excluded: []
:compileJava (Thread[Execution worker for ':',5,main]) started.

> Task :compileJava FAILED
Caching disabled for task ':compileJava' because:
  Build cache is disabled
Task ':compileJava' is not up-to-date because:
  Task has failed previously.
The input changes require a full rebuild for incremental task ':compileJava'.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with JDK Java compiler API.
/root/mc-bots/src/main/java/me/creepermaxcz/mcbots/Bot.java:4: error: package com.github.steveice10.mc.protocol.packet.ingame.clientbound does not exist
import com.github.steveice10.mc.protocol.packet.ingame.clientbound.ClientboundLoginPacket;
                                                                  ^
/root/mc-bots/src/main/java/me/creepermaxcz/mcbots/Bot.java:5: error: package com.github.steveice10.mc.protocol.packet.ingame.serverbound does not exist
import com.github.steveice10.mc.protocol.packet.ingame.serverbound.ServerboundChatPacket;
                                                                  ^
/root/mc-bots/src/main/java/me/creepermaxcz/mcbots/MainListener.java:3: error: package com.github.steveice10.mc.protocol.packet.ingame.clientbound does not exist
import com.github.steveice10.mc.protocol.packet.ingame.clientbound.ClientboundChatPacket;
                                                                  ^
/root/mc-bots/src/main/java/me/creepermaxcz/mcbots/Bot.java:41: error: method does not override or implement a method from a supertype
                @Override
                ^
/root/mc-bots/src/main/java/me/creepermaxcz/mcbots/Bot.java:43: error: cannot find symbol
                    if (packet instanceof ClientboundLoginPacket) {
                                          ^
  symbol: class ClientboundLoginPacket
/root/mc-bots/src/main/java/me/creepermaxcz/mcbots/Bot.java:69: error: cannot find symbol
        client.send(new ServerboundChatPacket(text));
                        ^
  symbol:   class ServerboundChatPacket
  location: class Bot
/root/mc-bots/src/main/java/me/creepermaxcz/mcbots/MainListener.java:11: error: MainListener is not abstract and does not override abstract method packetSent(PacketSentEvent) in SessionListener
public class MainListener implements SessionListener {
       ^
/root/mc-bots/src/main/java/me/creepermaxcz/mcbots/MainListener.java:17: error: method does not override or implement a method from a supertype
    @Override
    ^
/root/mc-bots/src/main/java/me/creepermaxcz/mcbots/MainListener.java:19: error: cannot find symbol
        if(packet instanceof ClientboundChatPacket) {
                             ^
  symbol:   class ClientboundChatPacket
  location: class MainListener
/root/mc-bots/src/main/java/me/creepermaxcz/mcbots/MainListener.java:20: error: cannot find symbol
            Component message = ((ClientboundChatPacket) packet).getMessage();
                                  ^
  symbol:   class ClientboundChatPacket
  location: class MainListener
/root/mc-bots/src/main/java/me/creepermaxcz/mcbots/MainListener.java:38: error: method does not override or implement a method from a supertype
    @Override
    ^
11 errors
:compileJava (Thread[Execution worker for ':',5,main]) completed. Took 0.378 secs.

FAILURE: Build failed with an exception.```

**Comment by crpmax** [comment]
Hello,
can you please provide me steps you have taken to try to compile it?

I compiled it in IntelliJ IDEA.

**Comment by json1c** [comment]
i executed command `gradle build`

**Comment by json1c** [comment]
??

**Comment by crpmax** [comment]
Please try it now again with current source.
It looks like there was a error with a renamed library.

**Comment by json1c** [comment]
it worked, thanks
